version: '3.8'

services:
  chatbot:
    build: .
    ports:
      - "9000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    env_file:
      - .env
    restart: unless-stopped
    command: python -m api 
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=busstop
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  mysql_data: 